before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar"
  - "java -jar selenium-server-standalone-2.53.1.jar &"

language: java

env:
  global:
    - SONATYPE_USERNAME=persado.com
    - secure: "hm2g5OVrhhL+Rd0yDI/QCsCRCxS0AsusS6q/BVsYE36LmBhSqnU/RkM5VAAyYPpv36HJZB4sVZfcwXG9XANv99QlgTBaqer4vbHW9f1aGGpwJ5/I9F71ypmRI9gJcyPyAi17SF0BL9afyLGfDvwsZc1P8wtsdd56a67pgxcykK0="

script: mvn clean install -DskipTests

after_success:
  - python src/scripts/addServer.py
  - mvn clean javadoc:jar source:jar deploy -DskipTests --settings ~/.m2/mySettings.xml
  
jdk:
  - openjdk8
  - openjdk11

